# -*- coding: utf-8 -*-
class Locators:
    BTN_COOKIES = "#axeptio_btn_acceptAll"
    HEADER = "header"
    LOGO = "header a[class*='Logo']"
    BTN_CONTACT = "header a.btn--nav"
    MENU_A_PROPOS = "header a[href*='a-propos']"
    HERO_TITLE = "h1"
    BTN_SE_LANCER = "a.btn--black"
    LINK_PAIEMENT = "a[href*='paiement']"
    FORM = "form"
    INPUT_NOM = "input[name='last_name']"
    INPUT_PRENOM = "input[name='first_name']"
    INPUT_EMAIL = "input[name='email']"
    INPUT_SOCIETE = "input[name='company']"
    INPUT_TELEPHONE = "input[name='mobile']"
    TEXTAREA_MESSAGE = "textarea[name='description']"
    BTN_SUBMIT = "button[type='submit']"
    FOOTER = "footer"
